version: '3.3'
services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        image: cms-backend
        container_name: csm-dev
        restart: unless-stopped
        env_file:
            - ./.env
        volumes:
            - .:/app
        depends_on:
            - mongo_db
            - postgres
        ports:
            - 8000:8000

    mongo_db:
        image: mongo:4.0.27-xenial
        container_name: csm-mongo
        restart: unless-stopped
        command: mongod --auth
        env_file:
            - ./.env
        ports:
            - 27017:27017
        volumes:
            - mongo_data:/data/db
    
    postgres:
        image: postgres:13-alpine
        container_name: csm-postgres
        restart: unless-stopped        
        env_file:
            - ./.env
        ports:
            - 5432:5432
        volumes:
            - pgdata:/var/lib/postgresql/data
                             
volumes:
    mongo_data:
        driver: local
    pgdata:
        driver: local